# Generated by Django 5.1.4 on 2025-01-21 02:42

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('center_name', models.CharField(max_length=255)),
                ('poc_email', models.EmailField(max_length=254)),
                ('poc_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None)),
                ('distribution_type', models.CharField(choices=[('food_bank', 'Food Bank'), ('urban_farm', 'Urban Farm'), ('individual_contributor', 'Individual Contributor'), ('other', 'Other')], max_length=255)),
                ('other_description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
